// Define constants to add/remove arduino functions from ruby
#define MRUBY_ARDUINO_DIGITAL_IO
#define MRUBY_ARDUINO_PINMODE
#define MRUBY_ARDUINO_DELAY
#define MRUBY_ARDUINO_SERIAL_PRINT
#define MRUBY_ARDUINO_SERIAL_PRINTLN

/* --- Leave the rest of this alone --- */
#ifdef MRUBY_ARDUINO_ALL
  #define MRUBY_ARDUINO_DIGITAL_IO
  #define MRUBY_ARDUINO_ANALOG_IO
  #define MRUBY_ARDUINO_SERIAL
  #define MRUBY_ARDUINO_SHIFT
  #define MRUBY_ARDUINO_INTERRUPTS
  #define MRUBY_ARDUINO_PINMODE
  #define MRUBY_ARDUINO_PULSE_IN
  #define MRUBY_ARDUINO_MILLIS
  #define MRUBY_ARDUINO_MICROS
  #define MRUBY_ARDUINO_DELAY
  #define MRUBY_ARDUINO_DELAY_MICROSECONDS
  #define MRUBY_ARDUINO_MAP
  #define MRUBY_ARDUINO_RANDOM_SEED
  #define MRUBY_ARDUINO_RANDOM
  #define MRUBY_ARDUINO_INTERRUPTS
#endif /*MRUBY_ARDUINO_ALL*/

#ifdef MRUBY_ARDUINO_DIGITAL_IO
  #define MRUBY_ARDUINO_DIGITAL_IO_CONSTANTS
  #define MRUBY_ARDUINO_PINMODE
  #define MRUBY_ARDUINO_DIGITAL_READ
  #define MRUBY_ARDUINO_DIGITAL_WRITE
#endif /*MRUBY_ARDUINO_DIGITAL_IO*/

#ifdef MRUBY_ARDUINO_ANALOG_IO
  #define MRUBY_ARDUINO_PINMODE
  #define MRUBY_ARDUINO_ANALOG_READ
  #define MRUBY_ARDUINO_ANALOG_WRITE
  #define MRUBY_ARDUINO_ANALOG_REFERENCE
#endif /*MRUBY_ARDUINO_ANALOG_IO*/

#ifdef MRUBY_ARDUINO_SERIAL
  #define MRUBY_ARDUINO_SERIAL_AVAILABLE
  #define MRUBY_ARDUINO_SERIAL_BEGIN
  #define MRUBY_ARDUINO_SERIAL_PRINT
  #define MRUBY_ARDUINO_SERIAL_PRINTLN
#endif /*MRUBY_ARDUINO_SERIAL*/

#if defined(MRUBY_ARDUINO_SERIAL_AVAILABLE) || defined(MRUBY_ARDUINO_SERIAL_BEGIN) || defined(MRUBY_ARDUINO_SERIAL_PRINT) || defined(MRUBY_ARDUINO_SERIAL_PRINTLN)
  #define MRUBY_ARDUINO_SERIAL_CLASS
#endif

#ifdef MRUBY_ARDUINO_SHIFT
  #define MRUBY_ARDUINO_SHIFT_CONSTANTS
  #define MRUBY_ARDUINO_SHIFT_IN
  #define MRUBY_ARDUINO_SHIFT_OUT
#endif /*MRUBY_ARDUINO_SERIAL*/

#ifdef MRUBY_ARDUINO_INTERRUPTS
  #define MRUBY_ARDUINO_NO_INTERRUPTS
#endif /*MRUBY_ARDUINO_INTERRUPTS*/

#ifdef MRUBY_ARDUINO_PINMODE
  #define MRUBY_ARDUINO_PINMODE_CONSTANTS
#endif /*MRUBY_ARDUINO_PINMODE*/
